apiVersion: v1
kind: Secret
metadata:
  name: postgresql-omero
type: kubernetes.io/basic-auth
stringData:
  username: omero
  password: ChAnGeMe

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: omero
      owner: omero
      secret:
        name: postgresql-omero
