apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "omero-server.name" . }}
    helm.sh/chart: {{ include "omero-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "omero-server.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omero-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omero-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # Autorestart when the configmap changes!
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          # In openmicroscopy/omero-server these CONFIG envvars have higher
          # precedence than .omero config files
            - name: CONFIG_omero_db_host
            {{- if .Values.databaseHost }}
              value: {{ .Values.databaseHost }}
            {{- else }}
              value: {{ .Release.Name }}-postgresql
            {{- end }}
            - name: CONFIG_omero_db_name
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: CONFIG_omero_db_user
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: CONFIG_omero_db_pass
              value: {{ .Values.postgresql.postgresqlPassword }}
            # Only used when initialising a new OMERO database
            - name: ROOTPASS
              value: {{ .Values.defaultRootPassword }}
          ports:
            # - name: ice-location
            #   containerPort: 4061
            #   protocol: TCP
            # - name: ice-router
            #   containerPort: 4063
            #   protocol: TCP
            - name: ice-srouter
              containerPort: 4064
              protocol: TCP
          livenessProbe:
            # Make this more lenient than readiness probe because failure
            # will restart the pod
            exec:
              command:
                - /opt/omero/server/OMERO.server/bin/omero
                - admin
                - status
            initialDelaySeconds: 300
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            # Controls whether pod will receive traffic
            exec:
              command:
                - /opt/omero/server/OMERO.server/bin/omero
                - admin
                - status
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /OMERO
              subPath: {{ .Values.persistence.subPath }}
            - name: omero-server-config
              mountPath: /opt/omero/server/config/server.omero
              subPath: server.omero
            - name: omero-server-var
              mountPath: /opt/omero/server/OMERO.server/var
      volumes:
        - name: omero-server-config
          configMap:
            name: omero-server-config
        - name: omero-server-var
          emptyDir: {}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: {{ include "omero-server.name" . }}
          helm.sh/chart: {{ include "omero-server.chart" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/managed-by: {{ .Release.Service }}
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
{{- end }}
